### ISSUE TITLE
Invalid attributes

### ISSUE THREAD

**Issue by aubreywullschleger** [Oncosm144/Capstone#2]
Important for errors!  Delete any `href` attributes on your `<img>` elements as these aren't valid attributes for an `<img>` element.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/<img src="">

Example: https://github.com/Oncosm144/Capstone/blob/master/index.html#L29-L32

Also, the `alt` attribute is not allowed on a `<video>` element, so I'd be sure to delete that. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video

**Comment by Oncosm144** [comment]
Invalid attributes removed.
